### ISSUE TITLE
Why stringify?

### ISSUE THREAD

**Issue by Charuru** [treygriffith/connect-mongodb#11]
You stringify the session before storing it. This makes it difficult to query in mongo, mongo can handle json. What am I missing? Thanks.

**Comment by masylum** [comment]
Hi Chararu. You are right and actually, if you check prior versions from this module you will see this is how it was working before.

I had to change because of issue #8. The new version of connect tries to do a merge and it fails on copying `data` as it doesn't have a setter defined.

https://github.com/senchalabs/connect/blob/master/lib/middleware/session/cookie.js#L25

If you can fork the project and try to have it working with the latest connect version, I will be very happy to merge it.

Thank's in advance!

**Comment by Charuru** [comment]
Ahh ok. Kinda hoping someone else take this. If this is going to happen it should happen quickly, as it's going to break people's code.

**Comment by mcfog** [comment]
tried to remove JSON.stringify and JSON.parse and it works well (with Connect 1.4.2

**Comment by masylum** [comment]
the new version works now ok without stringify... finally! :)
`npm update connect-mongodb` and clean your sessions database

**Comment by chrisgl** [comment]
Thanks for fixing the issue.
I got it working on my Laptop, but it doesn't work on my big machine.
The Version of connect is 1.4.2 and your Version is 0.4.0.
Any Idea where I find the point the data property, which still lands in the database, is written there?
How have you fixed that?
